#!/usr/bin/env bash

# Source this env to quickly build, clear and run by these aliases
# Run: source projenv

build() {
    if [ ! -d build ]; then
        mkdir build
        cmake -B build .
    fi
    if [ -z $1 ]; then
        clean
        cmake --build build
    else
        cmake --build build --target $1
    fi
    
}

clean() {
    if [ ! -d build ]; then
        echo "Error: Nothing to clean."
    else
        cmake --build build --target clean
    fi
}

c4ai() {
    exec_path="build/bin/c4ai"
    if [ -x $exec_path ]; then
        $exec_path $1 $2 $3 $4 $5
    else
        echo "Error: '$exec_path' not found. Build first!"
    fi
}

generator() {
    exec_path="build/bin/generator"
    if [ -x $exec_path ]; then
        $exec_path $1 $2 $3 $4 $5
    else
        echo "Error: '$exec_path' not found. Build first!"
    fi
}